import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { UserButton } from "@clerk/nextjs";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'OpenTrust',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-end mr-10 mt-5">
        <UserButton afterSignOutUrl="/" />
        </div>
        {children}
        </body>
    </html>
    </ClerkProvider>
  )
}
